sudo: false
language: cpp

compiler:
  - gcc
  - clang

install:
    - export g++="g++-4.8"; export gcc="gcc-4.8"
    - make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
