language: none
sudo: false

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5 GCOV=gcov-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
    - env: CXX=clang++-3.8 CC=clang-3.8 GCOV=gcov
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources

before_install:
  - pip install --user cpp-coveralls

install:
  - make
